/** Small, dependency-free formatting + export helpers (no logic, just display). */
import type { ContextItem, ContextPack } from "../types";

export function formatInt(n: number | undefined): string {
  if (n == null || !Number.isFinite(n)) return "—";
  return n.toLocaleString("en-US");
}

export function confidencePct(value: number): number {
  return Math.round(Math.max(0, Math.min(1, value)) * 100);
}

/** Copy text to the clipboard, resolving to whether it succeeded. */
export async function copyText(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    /* fall through to legacy path */
  }
  try {
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}

function lineRange(item: { lineStart?: number; lineEnd?: number }): string {
  if (item.lineStart == null) return "";
  if (item.lineEnd == null || item.lineEnd === item.lineStart) return `:${item.lineStart}`;
  return `:${item.lineStart}-${item.lineEnd}`;
}

function itemLine(item: ContextItem): string {
  return `- \`${item.sourcePath}${lineRange(item)}\` — **${item.label}** _(${item.reason}; ~${item.tokensEstimate} tok)_`;
}

/** Render a Context Pack as Markdown for the "Copy as Markdown" action. */
export function contextPackToMarkdown(pack: ContextPack): string {
  const lines: string[] = [];
  lines.push(`# Context Pack — ${pack.task}`);
  lines.push("");
  lines.push(
    `> mode: \`${pack.mode}\` · budget: ${formatInt(pack.budget)} tok · used: ${formatInt(
      pack.tokensUsed,
    )} tok · confidence: ${confidencePct(pack.confidence)}%`,
  );
  lines.push("");

  const section = (title: string, items: ContextItem[]): void => {
    if (items.length === 0) return;
    lines.push(`## ${title}`);
    for (const it of items) lines.push(itemLine(it));
    lines.push("");
  };

  section("Must read", pack.mustRead);
  section("Related docs", pack.relatedDocs);
  section("Data / tables", pack.tables);
  section("Tests", pack.tests);

  if (pack.risks.length > 0) {
    lines.push("## Risks");
    for (const r of pack.risks) lines.push(`- **[${r.level}] ${r.kind}** — ${r.message}`);
    lines.push("");
  }
  if (pack.excluded.length > 0) {
    lines.push("## Excluded (over budget)");
    for (const e of pack.excluded) lines.push(`- ${e.label} — _${e.reason}_`);
    lines.push("");
  }
  lines.push(`_Generated by Athar ${pack.atharVersion} · ${pack.generatedAt}_`);
  return lines.join("\n");
}

export function contextPackToJson(pack: ContextPack): string {
  return JSON.stringify(pack, null, 2);
}

/** Compact human label for a source location, e.g. "src/lib/oauth.ts:13-20". */
export function locationLabel(node: {
  sourcePath?: string;
  lineStart?: number;
  lineEnd?: number;
}): string {
  if (!node.sourcePath) return "";
  return `${node.sourcePath}${lineRange(node)}`;
}
