import { graphExists, readGraph } from "@kawngraph/core";
import type { KawnGraph, KawnNode } from "@kawngraph/shared";

/**
 * Deterministic context-bundle content for the non-MCP adapters (aider / generic).
 * Output is a pure function of the graph on disk (no timestamps), so a re-run only
 * rewrites the file when the graph actually changed.
 */

export const LOCAL_BASE_URLS: Record<"ollama" | "lmstudio", string> = {
  ollama: "http://localhost:11434/v1",
  lmstudio: "http://localhost:1234/v1",
};

/** A compact, human+agent-readable project map derived from the scanned graph. */
async function projectMap(root: string): Promise<string> {
  if (!(await graphExists(root))) {
    return "_No `.kawn/graph.json` yet — run `kawn scan` (or `kawn setup`) to build the map._";
  }
  const graph: KawnGraph = await readGraph(root);
  const byLayer = new Map<string, number>();
  for (const n of graph.nodes) byLayer.set(n.layer, (byLayer.get(n.layer) ?? 0) + 1);
  const layers = [...byLayer.entries()].sort((a, b) => b[1] - a[1]).map(([l, c]) => `${l} (${c})`).join(" · ");

  // Top files by degree (most-connected = most central to read first).
  const degree = new Map<string, number>();
  for (const e of graph.edges) {
    degree.set(e.from, (degree.get(e.from) ?? 0) + 1);
    degree.set(e.to, (degree.get(e.to) ?? 0) + 1);
  }
  const files = graph.nodes
    .filter((n: KawnNode) => n.type === "file")
    .map((n) => ({ path: n.sourcePath ?? n.label, deg: degree.get(n.id) ?? 0 }))
    .sort((a, b) => b.deg - a.deg)
    .slice(0, 12);

  const L: string[] = [];
  L.push(`- **Nodes:** ${graph.nodes.length} · **Edges:** ${graph.edges.length}`);
  L.push(`- **Layers:** ${layers}`);
  if (files.length) {
    L.push(`- **Most-connected files (read these first):**`);
    for (const f of files) L.push(`  - \`${f.path}\``);
  }
  return L.join("\n");
}

/** The Markdown context bridge an agent reads / a human pastes. */
export async function contextBridgeMarkdown(root: string): Promise<string> {
  const map = await projectMap(root);
  return `# KawnGraph — project context bridge

This file is generated by KawnGraph (\`kawn setup\`). It gives a coding agent a
fast map of this project so it can reach the right files without reading the whole
tree. **It is a fallback for tools that don't speak MCP** — tools that do (Claude
Code, Codex, Cursor, Copilot, Gemini CLI) get the same graph live over MCP.

## Get task-specific context

For any task, generate a focused, token-budgeted Context Pack:

\`\`\`bash
kawn pack "fix the OAuth callback" --format markdown   # paste into your agent
kawn pack "fix the OAuth callback" --format json       # for programmatic tools
kawn ask  "fix the OAuth callback"                     # human-readable summary
\`\`\`

Refresh this file after code changes with \`kawn update && kawn setup\`.

## Project map

${map}

---
_Generated by KawnGraph. Do not edit by hand — re-run \`kawn setup\` to refresh._
`;
}

/** The local-LLM endpoint config the `local` adapter writes (optional, no cloud). */
export function localLlmConfigJson(provider: "ollama" | "lmstudio", baseUrl: string | undefined, model: string | undefined): string {
  const config = {
    schema: "kawngraph.local-llm/v1",
    provider,
    baseUrl: baseUrl ?? LOCAL_BASE_URLS[provider],
    model: model ?? null,
    // KawnGraph never requires an LLM. This endpoint is used ONLY for optional
    // summarization/reranking when you pass `--local`; scanning/retrieval never
    // call it. No cloud, no API keys, no telemetry.
    usedFor: ["summarization", "reranking"],
    neverUsedFor: ["scanning", "required-retrieval"],
  };
  return JSON.stringify(config, null, 2) + "\n";
}
