import { makeOwnedFileAdapter } from "./ownedFile";
import type { AgentAdapter } from "../types";

/**
 * Generic / any-tool integration (prompt export).
 *
 * For tools that speak neither MCP nor a known context-file convention, the
 * integration IS the export: `kawn pack "<task>" --format markdown|json`. Setup
 * writes a short instructions file describing that workflow. Opt-in only (you ask
 * for it by name: `kawn setup generic`).
 */
const USING = `# Using KawnGraph with any tool

Your tool doesn't need MCP to benefit from KawnGraph. For any task, export the
same evidence-backed Context Pack and feed it to your tool or paste it into chat:

\`\`\`bash
kawn pack "fix the OAuth callback" --format markdown   # a ready-to-paste prompt
kawn pack "fix the OAuth callback" --format json       # for programmatic tools
kawn pack "fix the OAuth callback" --format markdown --out context.md
\`\`\`

The pack contains the few must-read files, related docs, tables, tests, risks, an
excluded list, and a confidence score — all under a token budget, deterministic,
no LLM required. Refresh the graph after code changes with \`kawn update\`.

---
_Generated by KawnGraph (\`kawn setup generic\`). Re-run to refresh._
`;

export const genericAdapter: AgentAdapter = makeOwnedFileAdapter({
  agent: "generic",
  displayName: "Generic / any tool",
  kind: "export",
  supports: { mcp: false, slashCommands: false, contextFiles: true, promptExport: true },
  autoSelectable: false,
  ownedKey: ".kawn/agent-context/USING-KAWN.md",
  configFormat: {
    file: ".kawn/agent-context/USING-KAWN.md",
    ownedKey: "(KawnGraph-owned export guide)",
    docUrl: "https://github.com/xd7fx/kawngraph/blob/main/docs/AGENTS.md",
    verifiedOn: "2026-06-24",
  },
  files: [{ relFile: ".kawn/agent-context/USING-KAWN.md", build: () => USING }],
  usage: () => [
    'Export task context for any tool: `kawn pack "<task>" --format markdown`',
    "JSON for programmatic use: `kawn pack \"<task>\" --format json`",
  ],
});
